# Generated by Django 4.2.6 on 2023-10-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 17, 11, 5, 58, 689010, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="expired_at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=6,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
