# Generated by Django 4.2.6 on 2023-10-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_token_expired_at_alter_token_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ORG_ADMIN", "organization admin"),
                    ("ORG_MANAGER", "organization managers"),
                    ("ORG_MEMBERS", "organization member"),
                    ("INTERNAL", "internal"),
                ],
                default="INTERNAL",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
