# Generated by Django 4.2.6 on 2023-10-22 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_username_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        11, message="The number should at least be 11 digit"
                    ),
                    django.core.validators.RegexValidator(
                        "^(\\+201|01|00201)[0-2,5]{1}[0-9]{8}",
                        message="Incorrect number format",
                    ),
                ],
                verbose_name="phone number",
            ),
        ),
    ]
