# Generated by Django 4.2.6 on 2023-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ORG_OWNER", "Organization owner"),
                    ("ORG_ADMIN", "Organization admin"),
                    ("ORG_MEMBER", "Organization member"),
                    ("INTERNAL", "Internal"),
                ],
                default="INTERNAL",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
