# Generated by Django 4.2.6 on 2023-10-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="email",
            field=models.EmailField(
                default=datetime.datetime(
                    2023, 10, 22, 10, 21, 58, 593294, tzinfo=datetime.timezone.utc
                ),
                max_length=254,
                verbose_name="invited email",
            ),
            preserve_default=False,
        ),
    ]
