# Generated by Django 4.2.6 on 2023-10-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_alter_organizationmember_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="organization name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=84,
                        unique=True,
                        verbose_name="organization slug",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization branch",
                "verbose_name_plural": "organization branches",
                "db_table": "org_branches",
            },
        ),
    ]
